name: Create Build main

on:
  push:
    branches:
      - main
    paths:
      - 'Frends.Pdf.Create/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.Pdf.Create
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
